version: '2'
services:
  redis-app:
    build: .
    ports:
      - "8080:8080"
    links:
      - "redis-server:redis"

  redis-server:
    image: "redis"
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - "$PWD/redis-data:/data"
